version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "jiradb"
      POSTGRES_USER: "" # todo: add username
      POSTGRES_PASSWORD: "" # todo: add password
      POSTGRES_ENCODING: 'UNICODE'
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_COLLATE: 'C'
      POSTGRES_COLLATE_TYPE: 'C'
    ports:
      - "5432:5432"

volumes:
  postgresqldata:
    external: false